name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout musl
        run: git submodule update --init --recursive third_party/musl

      - name: Install dependencies
        run: ./install_deps.sh

      - name: Build and verify VeriLoad
        run: make compile

      - name: Build musl
        run: make musl

      - name: Build tests
        run: make tests

      - name: Run
        run: ./run.sh
